require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FuelLoadsController do
  require "bigdecimal"
  require "bigdecimal/util"
  
  # This should return the minimal set of attributes required to create a valid
  # FuelLoad. As you add validations to FuelLoad, be sure to
  # update the return value of this method accordingly.
  
  before(:each) do
    @user = Factory(:user)
    test_sign_in(@user)
    @tractor = @user.tractors.build(Factory(:tractor))
    @tractor_driver = @user.tractor_drivers.build(Factory(:driver))
  end

  def valid_attributes
    { :amount => "120".to_d, :tractor_code => @tractor.code, :tractor_driver_name => @tractor_driver.name}
  end
  
  
  describe "GET index" do
    it "assigns all fuel_loads as @fuel_loads" do
      fuel_load = @user.fuel_load.build valid_attributes
      get :index
      assigns(:fuel_loads).should eq([fuel_load])
    end
  end

  describe "GET show" do
    it "assigns the requested fuel_load as @fuel_load" do
      fuel_load = @user.fuel_load.build valid_attributes
      get :show, :id => fuel_load.id.to_s
      assigns(:fuel_load).should eq(fuel_load)
    end
  end

  describe "GET new" do
    it "assigns a new fuel_load as @fuel_load" do
      get :new
      assigns(:fuel_load).should be_a_new(FuelLoad)
    end
  end

  describe "GET edit" do
    it "assigns the requested fuel_load as @fuel_load" do
      fuel_load = FuelLoad.create! valid_attributes
      get :edit, :id => fuel_load.id.to_s
      assigns(:fuel_load).should eq(fuel_load)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FuelLoad" do
        expect {
          post :create, :fuel_load => valid_attributes
        }.to change(FuelLoad, :count).by(1)
      end

      it "assigns a newly created fuel_load as @fuel_load" do
        post :create, :fuel_load => valid_attributes
        assigns(:fuel_load).should be_a(FuelLoad)
        assigns(:fuel_load).should be_persisted
      end

      it "redirects to the created fuel_load" do
        post :create, :fuel_load => valid_attributes
        response.should redirect_to(FuelLoad.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved fuel_load as @fuel_load" do
        # Trigger the behavior that occurs when invalid params are submitted
        FuelLoad.any_instance.stub(:save).and_return(false)
        post :create, :fuel_load => {}
        assigns(:fuel_load).should be_a_new(FuelLoad)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FuelLoad.any_instance.stub(:save).and_return(false)
        post :create, :fuel_load => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested fuel_load" do
        fuel_load = FuelLoad.create! valid_attributes
        # Assuming there are no other fuel_loads in the database, this
        # specifies that the FuelLoad created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FuelLoad.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => fuel_load.id, :fuel_load => {'these' => 'params'}
      end

      it "assigns the requested fuel_load as @fuel_load" do
        fuel_load = FuelLoad.create! valid_attributes
        put :update, :id => fuel_load.id, :fuel_load => valid_attributes
        assigns(:fuel_load).should eq(fuel_load)
      end

      it "redirects to the fuel_load" do
        fuel_load = FuelLoad.create! valid_attributes
        put :update, :id => fuel_load.id, :fuel_load => valid_attributes
        response.should redirect_to(fuel_load)
      end
    end

    describe "with invalid params" do
      it "assigns the fuel_load as @fuel_load" do
        fuel_load = FuelLoad.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FuelLoad.any_instance.stub(:save).and_return(false)
        put :update, :id => fuel_load.id.to_s, :fuel_load => {}
        assigns(:fuel_load).should eq(fuel_load)
      end

      it "re-renders the 'edit' template" do
        fuel_load = FuelLoad.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FuelLoad.any_instance.stub(:save).and_return(false)
        put :update, :id => fuel_load.id.to_s, :fuel_load => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested fuel_load" do
      fuel_load = FuelLoad.create! valid_attributes
      expect {
        delete :destroy, :id => fuel_load.id.to_s
      }.to change(FuelLoad, :count).by(-1)
    end

    it "redirects to the fuel_loads list" do
      fuel_load = FuelLoad.create! valid_attributes
      delete :destroy, :id => fuel_load.id.to_s
      response.should redirect_to(fuel_loads_url)
    end
  end

end
